%macro APPLY 4
	clc
	%assign i 0
	%assign count %4/64
	%rep count
	%if i > count
	%exitrep
	%endif

	mov rax,  	[%2+i*8]
	adc rax,  	[%3+i*8]
	mov [%1+i*8], 	rax
	%assign i i+1
	%endrep
%endmacro
%macro READ 2-3 1
mov rdi, %3
mov rsi, %1
mov rdx, %2
mov rax, 0
syscall
%endmacro
%macro WRITE 2-3 1
mov rdi, %3
mov rsi, %1
mov rdx, %2
mov rax, 1
syscall
%endmacro
%macro EXIT 0-1 0
mov rdi, %1
mov rax, 60
syscall
%endmacro